<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Image extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Image_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'image/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'image/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'image/index.html';
            $config['first_url'] = base_url() . 'image/index.html';
        }

        $config['per_page'] = 100000000;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Image_model->total_rows($q);
        $image = $this->Image_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'image_data' => $image,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('image/image_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Image_model->get_by_id($id);
        if ($row) {
            $data = array(
		'image' => $row->image,
		'name' => $row->name,
	    );
            $this->load->view('image/image_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('image/create_action'),
	    'image' => set_value('image'),
	    'name' => set_value('name'),
	);
        $this->load->view('image/image_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Image_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('image'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Image_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('image/update_action'),
		'image' => set_value('image', $row->image),
		'name' => set_value('name', $row->name),
	    );
            $this->load->view('image/image_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('image', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Image_model->update($this->input->post('image', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('image'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Image_model->get_by_id($id);

        if ($row) {
            $this->Image_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('image'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');

	$this->form_validation->set_rules('image', 'image', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Image.php */
/* Location: ./application/controllers/Image.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-04 02:28:51 */
/* http://harviacode.com */
