<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Image_produk extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Image_produk_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'image_produk/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'image_produk/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'image_produk/index.html';
            $config['first_url'] = base_url() . 'image_produk/index.html';
        }

        $config['per_page'] = 100000000;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Image_produk_model->total_rows($q);
        $image_produk = $this->Image_produk_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'image_produk_data' => $image_produk,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('image_produk/image_produk_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Image_produk_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'image' => $row->image,
	    );
            $this->load->view('image_produk/image_produk_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image_produk'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('image_produk/create_action'),
	    'id' => set_value('id'),
	    'image' => set_value('image'),
	);
        $this->load->view('image_produk/image_produk_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id' => $this->input->post('id',TRUE),
		'image' => $this->input->post('image',TRUE),
	    );

            $this->Image_produk_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('image_produk'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Image_produk_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('image_produk/update_action'),
		'id' => set_value('id', $row->id),
		'image' => set_value('image', $row->image),
	    );
            $this->load->view('image_produk/image_produk_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image_produk'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'id' => $this->input->post('id',TRUE),
		'image' => $this->input->post('image',TRUE),
	    );

            $this->Image_produk_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('image_produk'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Image_produk_model->get_by_id($id);

        if ($row) {
            $this->Image_produk_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('image_produk'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('image_produk'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id', 'id', 'trim|required');
	$this->form_validation->set_rules('image', 'image', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Image_produk.php */
/* Location: ./application/controllers/Image_produk.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-04 02:28:51 */
/* http://harviacode.com */
