<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembelian_produk_model extends CI_Model
{

    public $table = 'pembelian_produk';
    public $id = 'id_pembelian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
		$this->db->select("*");
		$this->db->select("pembelian_produk.bukti_pembayaran as bukti_pembayaran1");
		$this->db->select("pembelian_produk.status_pembayaran as status_pembayaran1");
        $this->db->join('topik', 'pembelian_produk.id_produk = topik.id', 'left')
			->join('pembelian', 'pembelian_produk.pembelian_id_pembelian = pembelian.id_pembelian', 'left')
			->join('users', 'pembelian.users_id = users_id', 'left')
			->where('pembelian_produk.id_pembelian', $id);
        return $this->db->get($this->table)->row();
    }


	function get_by_idd($id)
	{

		$this->db->where('pembelian_produk.id_pembelian', $id);
		return $this->db->get($this->table)->row();
	}
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pembelian', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('pembelian_id_pembelian', $q);
	$this->db->or_like('bukti_pembayaran', $q);
	$this->db->or_like('status_pembayaran', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pembelian', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('pembelian_id_pembelian', $q);
	$this->db->or_like('bukti_pembayaran', $q);
	$this->db->or_like('status_pembayaran', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_limit_data1() {
		;
        return $this->db->get_where('pembelian_produk', array('status_pembayaran' => 'no'))->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembelian_produk_model.php */
/* Location: ./application/models/Pembelian_produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-04 05:00:10 */
/* http://harviacode.com */
