<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ruangan_model extends CI_Model
{

    public $table = 'ruangan';
    public $id = 'idruangan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
		$this->db->select("*");
		$this->db->join('topik', 'ruangan.topik_id = topik.id', 'left')
			->where('ruangan.idruangan', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idruangan', $q);
	$this->db->or_like('nama_ruangan', $q);
	$this->db->or_like('link_zoom', $q);
	$this->db->or_like('informasi', $q);
	$this->db->or_like('topik_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idruangan', $q);
	$this->db->or_like('nama_ruangan', $q);
	$this->db->or_like('link_zoom', $q);
	$this->db->or_like('informasi', $q);
	$this->db->or_like('topik_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

	function get_limit_data1() {

		return $this->db->query("SELECT pembelian_produk.id_pembelian as id_pembelian ,users.name as name, users.email as email FROM pembelian_produk LEFT JOIN pembelian ON pembelian_produk.pembelian_id_pembelian=pembelian.id_pembelian
LEFT JOIN users ON pembelian.users_id=users.id")->result();
	}

	function get_limit_data2() {

		return $this->db->query("SELECT * FROM ruangan")->result();
	}

	function get_limit_data3() {

		return $this->db->query("SELECT pembelian_paket.id_pembelian as id_pembelian ,users.name as name, users.email as email FROM pembelian_paket LEFT JOIN pembelian ON pembelian_paket.pembelian_id_pembelian=pembelian.id_pembelian
LEFT JOIN users ON pembelian.users_id=users.id")->result();
	}

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ruangan_model.php */
/* Location: ./application/models/Ruangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-11 05:46:13 */
/* http://harviacode.com */
